In [1]:
import polars as pl

In [3]:
p = r'C:\Users\natha\OneDrive\Desktop\atx\data\us_split_adjustment_factors_common200\split_events_by_symbol\symbol=AAPL\data_0.parquet'
df = pl.read_parquet(p)
df

shape: (5, 3)
┌────────┬────────────┬──────────────┐
│ symbol ┆ date       ┆ split_factor │
│ ---    ┆ ---        ┆ ---          │
│ str    ┆ date       ┆ f64          │
╞════════╪════════════╪══════════════╡
│ AAPL   ┆ 1987-06-16 ┆ 0.5          │
│ AAPL   ┆ 2000-06-21 ┆ 0.5          │
│ AAPL   ┆ 2005-02-28 ┆ 0.5          │
│ AAPL   ┆ 2014-06-09 ┆ 0.142857     │
│ AAPL   ┆ 2020-08-31 ┆ 0.25         │
└────────┴────────────┴──────────────┘

In [6]:
p = r'C:\Users\natha\OneDrive\Desktop\atx\data\us_split_adjustment_factors\security_master\security_master.parquet'
pl.scan_parquet(p).filter(pl.col('symbol') == 'RIOT').collect()

shape: (2_566, 15)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ date       ┆ symbol ┆ cumulative ┆ cash_divi ┆ … ┆ gics_sect ┆ gics_sect ┆ gics_sub_ ┆ gics_sour │
│ ---        ┆ ---    ┆ _adjustmen ┆ dend      ┆   ┆ or_code   ┆ or        ┆ industry  ┆ ce        │
│ date       ┆ str    ┆ t_factor   ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆        ┆ ---        ┆ f64       ┆   ┆ str       ┆ str       ┆ str       ┆ str       │
│            ┆        ┆ f64        ┆           ┆   ┆           ┆           ┆           ┆           │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2016-03-31 ┆ RIOT   ┆ 1.0        ┆ 0.0       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2016-04-01 ┆ RIOT   ┆ 1.0        ┆ 0.0       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2016-04-04 ┆ RIOT   ┆ 1.0        ┆ 0.0       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2016-04-05 ┆ RIOT   ┆ 1.0        ┆ 0.0       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2016-04-06 ┆ RIOT   ┆ 1.0        ┆ 0.0       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2026-06-08 ┆ RIOT   ┆ 1.0        ┆ 0.0       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2026-06-09 ┆ RIOT   ┆ 1.0        ┆ 0.0       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2026-06-10 ┆ RIOT   ┆ 1.0        ┆ 0.0       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2026-06-11 ┆ RIOT   ┆ 1.0        ┆ 0.0       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2026-06-12 ┆ RIOT   ┆ 1.0        ┆ 0.0       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘